#spring.application.name=GreenForum
spring:
  jwt:
    secret: 12345678qwertyui12345678qwertyui12345678qwertyui
    lifetime: 30m

  datasource:
    url: jdbc:postgresql://localhost:5432/green-db
    username: postgres
    password: 1111
#    url: jdbc:h2:mem:green-db
#    driverClassName: org.h2.Driver

  flyway:
    enabled: true
    locations:
      - db.migration

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
